name: Generate Snake from Contributions

on:
  schedule:
    # 매 24시간마다
    - cron: '0 */24 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  generate:
    name: Generate snake.svg
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate GitHub contributions snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: G-Jin12
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
